const sampleListings = [
  {
    title: "Furnished Studio in HSR Layout",
    description: "Sleek sunlit studio flat in Bangalore's tech hub with modular kitchen, 100 Mbps Wi-Fi, power backup, and dedicated work desk.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    },
    price: 18000,
    location: "HSR Layout, Bangalore",
    country: "Karnataka",
    roomType: "studio",
    furnished: "furnished",
    genderPreference: "any",
    preferredTenants: "professionals",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: true },
    rules: { smoking: false, pets: true, guests: true, curfew: false },
    securityDeposit: 36000,
    minStayMonths: 6,
    bills: { included: true, details: "High-speed Wi-Fi, water, and building maintenance included." }
  },
  {
    title: "Private Room in 3BHK Flat",
    description: "Spacious private master bedroom with attached washroom and private balcony in a gated society in Koramangala.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=80",
    },
    price: 14500,
    location: "Koramangala, Bangalore",
    country: "Karnataka",
    roomType: "single",
    furnished: "furnished",
    genderPreference: "any",
    preferredTenants: "professionals",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: true },
    rules: { smoking: false, pets: false, guests: true, curfew: false },
    securityDeposit: 25000,
    minStayMonths: 3,
    bills: { included: true, details: "Wi-Fi and maid service split equally." }
  },
  {
    title: "Luxury 2BHK Apartment for Rent",
    description: "Modern 2BHK flat with wooden flooring, smart TV, modular kitchen, swimming pool access, and covered car parking in Bandra.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    },
    price: 45000,
    location: "Bandra West, Mumbai",
    country: "Maharashtra",
    roomType: "entire_apartment",
    furnished: "furnished",
    genderPreference: "any",
    preferredTenants: "family",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: true },
    rules: { smoking: false, pets: true, guests: true, curfew: false },
    securityDeposit: 90000,
    minStayMonths: 11,
    bills: { included: false, details: "Electricity and gas as per meter reading." }
  },
  {
    title: "Shared Student Room near Campus",
    description: "Twin-sharing fully furnished room for students near North Campus with 3 times food, daily housekeeping, and zero brokerage.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80",
    },
    price: 8500,
    location: "North Campus, Delhi",
    country: "Delhi NCR",
    roomType: "shared",
    furnished: "furnished",
    genderPreference: "any",
    preferredTenants: "students",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: false },
    rules: { smoking: false, pets: false, guests: false, curfew: true },
    securityDeposit: 8500,
    minStayMonths: 6,
    bills: { included: true, details: "Food, Wi-Fi, electricity and water all included." }
  },
  {
    title: "Executive 1BHK in Cyber City",
    description: "Chic 1BHK apartment walking distance from DLF Cyber Hub. Fitted with high-end appliances, gym access, and 24/7 security.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
    },
    price: 28000,
    location: "Cyber City, Gurgaon",
    country: "Haryana",
    roomType: "studio",
    furnished: "furnished",
    genderPreference: "any",
    preferredTenants: "professionals",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: true },
    rules: { smoking: false, pets: false, guests: true, curfew: false },
    securityDeposit: 56000,
    minStayMonths: 6,
    bills: { included: true, details: "Wi-Fi and society maintenance included." }
  },
  {
    title: "Cozy Single Room in Indiranagar",
    description: "Private single room in a peaceful residential street in Indiranagar. Steps away from metro, cafes, and 100ft Road.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1540518614846-7ede433c4ef2?auto=format&fit=crop&w=800&q=80",
    },
    price: 13000,
    location: "Indiranagar, Bangalore",
    country: "Karnataka",
    roomType: "single",
    furnished: "furnished",
    genderPreference: "any",
    preferredTenants: "professionals",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: false, laundry: true, parking: true },
    rules: { smoking: false, pets: true, guests: true, curfew: false },
    securityDeposit: 26000,
    minStayMonths: 3,
    bills: { included: true, details: "High-speed fiber internet and water included." }
  },
  {
    title: "Gated Society 3BHK Flat in Gachibowli",
    description: "Spacious 3BHK flat in a premium high-rise society in Hyderabad's Financial District with clubhouse, tennis court, and security.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    },
    price: 38000,
    location: "Gachibowli, Hyderabad",
    country: "Telangana",
    roomType: "entire_apartment",
    furnished: "semi-furnished",
    genderPreference: "any",
    preferredTenants: "family",
    immediateAvailability: true,
    availableFrom: "2026-10-15",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: true },
    rules: { smoking: false, pets: true, guests: true, curfew: false },
    securityDeposit: 76000,
    minStayMonths: 11,
    bills: { included: false, details: "Maintenance ₹3,500/month." }
  },
  {
    title: "Modern Co-living Studio in Hinjawadi",
    description: "Hassle-free managed studio room near Hinjawadi IT Park Phase 1. Includes daily breakfast, weekly cleaning, and gaming lounge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
    },
    price: 15500,
    location: "Hinjawadi, Pune",
    country: "Maharashtra",
    roomType: "studio",
    furnished: "furnished",
    genderPreference: "any",
    preferredTenants: "professionals",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: true },
    rules: { smoking: false, pets: false, guests: true, curfew: false },
    securityDeposit: 15500,
    minStayMonths: 1,
    bills: { included: true, details: "All bills, electricity up to 100 units, and meals included." }
  },
  {
    title: "Sunlit Master Bedroom in Powai",
    description: "Ensuite private master room with lake views in Hiranandani Powai. Fully furnished with king bed, wardrobe, and attached bathroom.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=800&q=80",
    },
    price: 22000,
    location: "Powai, Mumbai",
    country: "Maharashtra",
    roomType: "ensuite",
    furnished: "furnished",
    genderPreference: "any",
    preferredTenants: "professionals",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: true },
    rules: { smoking: false, pets: false, guests: true, curfew: false },
    securityDeposit: 44000,
    minStayMonths: 6,
    bills: { included: true, details: "Society maintenance and high-speed Wi-Fi included." }
  },
  {
    title: "Furnished 1BHK Flat near OMR",
    description: "Independent 1BHK flat close to Sholinganallur junction. Ideal for IT employees seeking quick commute and quiet neighborhood.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    },
    price: 16000,
    location: "OMR, Chennai",
    country: "Tamil Nadu",
    roomType: "entire_apartment",
    furnished: "furnished",
    genderPreference: "any",
    preferredTenants: "any",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: true },
    rules: { smoking: false, pets: true, guests: true, curfew: false },
    securityDeposit: 32000,
    minStayMonths: 6,
    bills: { included: true, details: "Water and building maintenance included." }
  },
  {
    title: "Spacious Private Room in Viman Nagar",
    description: "Well-ventilated private room in a modern 3BHK flat near Symbiosis College and Pune Airport. Walking distance to Phoenix Marketcity.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=80",
    },
    price: 12500,
    location: "Viman Nagar, Pune",
    country: "Maharashtra",
    roomType: "single",
    furnished: "furnished",
    genderPreference: "any",
    preferredTenants: "any",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: true },
    rules: { smoking: false, pets: true, guests: true, curfew: false },
    securityDeposit: 20000,
    minStayMonths: 3,
    bills: { included: true, details: "Wi-Fi and water bills included." }
  },
  {
    title: "Minimalist Studio near Sector 62",
    description: "Compact, well-designed 1RK studio apartment with kitchen setup and separate work corner. Perfect for single professionals.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80",
    },
    price: 14000,
    location: "Sector 62, Noida",
    country: "Uttar Pradesh",
    roomType: "studio",
    furnished: "furnished",
    genderPreference: "any",
    preferredTenants: "professionals",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: true },
    rules: { smoking: false, pets: false, guests: true, curfew: false },
    securityDeposit: 20000,
    minStayMonths: 3,
    bills: { included: true, details: "Building maintenance and Wi-Fi included." }
  },
  {
    title: "Designer 2BHK Flat in Whitefield",
    description: "Spacious 2BHK with wooden accents, modular island kitchen, and balcony overlooking lush green community gardens near ITPL.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80",
    },
    price: 32000,
    location: "Whitefield, Bangalore",
    country: "Karnataka",
    roomType: "entire_apartment",
    furnished: "furnished",
    genderPreference: "any",
    preferredTenants: "family",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: true },
    rules: { smoking: false, pets: true, guests: true, curfew: false },
    securityDeposit: 64000,
    minStayMonths: 11,
    bills: { included: false, details: "Electricity as per BESCOM meter." }
  },
  {
    title: "Cozy Furnished Room in South Extension",
    description: "Centrally located single private room in South Extension Part 2. Easy access to AIIMS, Metro Pink Line, and market amenities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80",
    },
    price: 15000,
    location: "South Extension, Delhi",
    country: "Delhi NCR",
    roomType: "single",
    furnished: "furnished",
    genderPreference: "female",
    preferredTenants: "students",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: false },
    rules: { smoking: false, pets: false, guests: false, curfew: true },
    securityDeposit: 15000,
    minStayMonths: 6,
    bills: { included: true, details: "High-speed Wi-Fi and water bills included." }
  },
  {
    title: "Modern Loft Studio in C-Scheme",
    description: "Aesthetic loft studio with exposed brick walls, smart study desk, and rooftop cafe access in the heart of Jaipur.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=800&q=80",
    },
    price: 16500,
    location: "C-Scheme, Jaipur",
    country: "Rajasthan",
    roomType: "studio",
    furnished: "furnished",
    genderPreference: "any",
    preferredTenants: "any",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: true },
    rules: { smoking: false, pets: true, guests: true, curfew: false },
    securityDeposit: 25000,
    minStayMonths: 3,
    bills: { included: true, details: "Water, Wi-Fi, and housekeeping included." }
  },
  {
    title: "Luxury Gated Society 2BHK in Andheri",
    description: "Well-appointed 2BHK flat in Lokhandwala Complex with gym, 2 covered parking slots, and round-the-clock CCTV surveillance.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    },
    price: 52000,
    location: "Andheri West, Mumbai",
    country: "Maharashtra",
    roomType: "entire_apartment",
    furnished: "furnished",
    genderPreference: "any",
    preferredTenants: "professionals",
    immediateAvailability: true,
    availableFrom: "2026-10-01",
    amenities: { attachedBathroom: true, kitchenAccess: true, wifi: true, ac: true, laundry: true, parking: true },
    rules: { smoking: false, pets: false, guests: true, curfew: false },
    securityDeposit: 100000,
    minStayMonths: 11,
    bills: { included: false, details: "Society maintenance ₹4,000/month." }
  }
];

module.exports = { data: sampleListings };